include:
    - Guardian            # Inspect all Swift files under "Guardian/"

exclude:
    - '**Tests.swift'   # Ignore Swift files that end in "Tests"
    - Carthage   # Ignore Swift files under "Source/Carthage/"

# Tailor will check for violations to all rules except for the following ones
except:
    - trailing-whitespace
    - terminating-newline